"""Render the escalation memo as a print-ready PDF.

The memo's audience is a credit officer, not a developer — markdown means
nothing to them. This renderer typesets the synthesized memo (headings,
findings table, lists, methodology note) as a branded lender-file document.

Font strategy: use a Unicode TTF when available (Windows Arial, Linux
DejaVu/Liberation); otherwise fall back to core Helvetica with a small
transliteration map so characters like ≥ or — never crash a deployment.
"""

import re
from pathlib import Path

from fpdf import FPDF

from app.agent.state import AuditState

FONT_CANDIDATES = [
    (r"C:\Windows\Fonts\arial.ttf", r"C:\Windows\Fonts\arialbd.ttf"),
    (
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    ),
    (
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    ),
]

_TRANSLIT = {"—": "-", "–": "-", "’": "'", "‘": "'", "“": '"', "”": '"',
             "≥": ">=", "≤": "<=", "€": "EUR", "·": "-", "→": "->", "✓": "OK"}


class MemoPDF(FPDF):
    def __init__(self, borrower_line: str, footer_note: str) -> None:
        super().__init__(format="A4")
        self.borrower_line = borrower_line
        self.footer_note = footer_note
        self.family_name = "helvetica"
        self.unicode_ok = False
        self.set_margins(20, 18, 20)
        self.set_auto_page_break(auto=True, margin=24)
        for regular, bold in FONT_CANDIDATES:
            if Path(regular).exists() and Path(bold).exists():
                self.add_font("Memo", "", regular)
                self.add_font("Memo", "B", bold)
                self.family_name = "Memo"
                self.unicode_ok = True
                break

    def clean(self, text: str) -> str:
        if self.unicode_ok:
            return text
        for src, dst in _TRANSLIT.items():
            text = text.replace(src, dst)
        return text.encode("latin-1", errors="replace").decode("latin-1")

    def header(self) -> None:
        self.set_font(self.family_name, "B", 9)
        self.set_text_color(5, 150, 105)
        self.cell(85, 5, "CovenantSentinel", align="L", new_x="RIGHT", new_y="TOP")
        self.set_font(self.family_name, "", 7.5)
        self.set_text_color(120, 120, 120)
        self.cell(85, 5, "CONFIDENTIAL - Credit risk escalation", align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(20, self.get_y() + 1, 190, self.get_y() + 1)
        self.ln(5)
        self.set_text_color(20, 20, 20)
        self.set_x(self.l_margin)

    def footer(self) -> None:
        self.set_y(-18)
        self.set_font(self.family_name, "", 7)
        self.set_text_color(130, 130, 130)
        self.multi_cell(0, 3.6, self.clean(self.footer_note), align="C", new_x="LMARGIN", new_y="NEXT")
        self.cell(0, 4, f"Page {self.page_no()} of {{nb}}", align="C")


_INLINE_EMPHASIS = re.compile(r"(?<!\*)\*(?!\*)([^*]+)\*(?!\*)")


def _prep_inline(text: str) -> str:
    """Keep **bold** (rendered via markdown=True); drop single-star emphasis."""
    return _INLINE_EMPHASIS.sub(r"\1", text).replace("\\*", "*")


def _table_block(lines: list[str], start: int) -> tuple[list[list[str]], int]:
    rows: list[list[str]] = []
    index = start
    while index < len(lines) and lines[index].strip().startswith("|"):
        cells = [c.strip() for c in lines[index].strip().strip("|").split("|")]
        if not all(re.fullmatch(r":?-{2,}:?", c) for c in cells):  # skip separator row
            rows.append([re.sub(r"\*+", "", c) for c in cells])
        index += 1
    return rows, index


def memo_to_pdf(state: AuditState) -> bytes:
    memo = state.memo_markdown or ""
    lines = memo.splitlines()
    title = next((l[2:].strip() for l in lines if l.startswith("# ")), "Covenant Compliance Memo")
    confidence = round((state.overall_confidence or 0) * 100)
    footer_note = (
        f"Generated by CovenantSentinel (run {state.run_id}) - overall confidence {confidence}% - "
        "every figure computed by deterministic tools and verified against cited sources"
    )

    pdf = MemoPDF(title, footer_note)
    pdf.alias_nb_pages()
    pdf.add_page()
    family = pdf.family_name

    index = 0
    while index < len(lines):
        raw = lines[index]
        stripped = raw.strip()
        pdf.set_x(pdf.l_margin)

        if not stripped:
            pdf.ln(1.8)
            index += 1
            continue
        if stripped.startswith("|"):
            rows, index = _table_block(lines, index)
            if rows:
                pdf.set_font(family, "", 8.6)
                with pdf.table(
                    first_row_as_headings=True,
                    line_height=5.4,
                    text_align="LEFT",
                    borders_layout="HORIZONTAL_LINES",
                    padding=1.2,
                ) as table:
                    for cells in rows:
                        row = table.row()
                        for cell in cells:
                            row.cell(pdf.clean(cell))
                pdf.ln(1.5)
            continue
        if stripped.startswith("# "):
            pdf.set_font(family, "B", 13.5)
            pdf.multi_cell(0, 6.4, pdf.clean(stripped[2:].strip()), new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1.2)
        elif stripped.startswith("## "):
            pdf.ln(1.6)
            pdf.set_font(family, "B", 10.5)
            pdf.set_text_color(5, 120, 90)
            pdf.multi_cell(0, 5.6, pdf.clean(stripped[3:].strip().upper()), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(20, 20, 20)
            pdf.ln(0.4)
        elif stripped.startswith("---"):
            pdf.ln(1.2)
            pdf.set_draw_color(200, 200, 200)
            pdf.line(20, pdf.get_y(), 190, pdf.get_y())
            pdf.ln(2.2)
        elif re.match(r"^\d+\.\s+", stripped):
            number, body = stripped.split(".", 1)
            pdf.set_font(family, "", 9.3)
            pdf.set_x(pdf.l_margin + 3)
            pdf.multi_cell(
                0, 4.9, pdf.clean(_prep_inline(f"{number}. {body.strip()}")),
                new_x="LMARGIN", new_y="NEXT", markdown=pdf.unicode_ok,
            )
            pdf.ln(0.6)
        elif stripped.startswith(("- ", "* ")):
            pdf.set_font(family, "", 9.3)
            pdf.set_x(pdf.l_margin + 3)
            bullet = "• " if pdf.unicode_ok else "- "
            pdf.multi_cell(
                0, 4.9, pdf.clean(bullet + _prep_inline(stripped[2:].strip())),
                new_x="LMARGIN", new_y="NEXT", markdown=pdf.unicode_ok,
            )
            pdf.ln(0.6)
        elif stripped.startswith("*") and stripped.endswith("*") and "Methodology" in stripped:
            pdf.set_font(family, "", 7.8)
            pdf.set_text_color(110, 110, 110)
            pdf.multi_cell(0, 4.2, pdf.clean(stripped.strip("*")), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(20, 20, 20)
        else:
            pdf.set_font(family, "", 9.3)
            pdf.multi_cell(
                0, 4.9, pdf.clean(_prep_inline(stripped)),
                new_x="LMARGIN", new_y="NEXT", markdown=pdf.unicode_ok,
            )
        index += 1

    return bytes(pdf.output())
